export const Data2014 = [
    {
      id: "2014-1",
      linkedinUrl: "https://www.linkedin.com/in/deborshideb/",
      studentName: "Deborshi Deb",
      role: "Senior Dev",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-2",
      linkedinUrl: "https://www.linkedin.com/in/nareshkumarjyani/",
      studentName: "Naresh Kumar",
      role: "Associate - Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-3",
      linkedinUrl: "https://www.linkedin.com/in/singh--nishant/",
      studentName: "Nishant Singh",
      role: "Senior Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-4",
      linkedinUrl: "https://www.linkedin.com/in/sachingahlawat/",
      studentName: "Sachin Gahlawat",
      role: "Digital Marketing Manager",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-5",
      linkedinUrl: "https://www.linkedin.com/in/shreya-singh10/",
      studentName: "Shreya Singh",
      role: "Frontend Developer and Tech Content Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-6",
      linkedinUrl: "https://www.linkedin.com/in/avrinderkaur/",
      studentName: "Avrinder Kaur",
      role: "Senior Consultant",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-7",
      linkedinUrl: "https://www.linkedin.com/in/mehul20042001/",
      studentName: "Mehul Kulshrestha",
      role: "Senior Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-8",
      linkedinUrl: "https://www.linkedin.com/in/nippon-patel-np23/",
      studentName: "Nippon Patel",
      role: "Enterprise Resources Planning Specialist",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-9",
      linkedinUrl: "https://www.linkedin.com/in/aakanksha-pachauri-a7732b96/",
      studentName: "Aakanksha Pachauri",
      role: "Application Support Analyst",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-10",
      linkedinUrl: "https://www.linkedin.com/in/ankesh93/",
      studentName: "Ankesh Gupta",
      role: "Staff Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-11",
      linkedinUrl: "https://www.linkedin.com/in/neha-ghatia-14420491/",
      studentName: "Neha Ghatia",
      role: "Data Scientist",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2014-12",
      linkedinUrl: "https://www.linkedin.com/in/ankitmt01/",
      studentName: "Ankit Gupta",
      role: "Test Environment Management",
      companyLogoUrl: "",
      profileImage: "",
    },
  ];
  
// ==================================================================================================

export const Data2015 = [
    {
      id: "2015-1",
      linkedinUrl: "https://www.linkedin.com/in/lordzuko/",
      studentName: "Himanshu Maurya",
      role: "AIML Language Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2015-2",
      linkedinUrl: "https://www.linkedin.com/in/aishwarya2khandelwal/",
      studentName: "Aishwarya ",
      role: "Solutions Consultant",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2015-3",
      linkedinUrl: "https://www.linkedin.com/in/prakhar927/",
      studentName: "Prakhar Shrivastav",
      role: "Chief Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2015-4",
      linkedinUrl: "https://www.linkedin.com/in/shastrigaurav95/",
      studentName: "Gaurav Shastri",
      role: "Engineering Lead",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2015-5",
      linkedinUrl: "https://www.linkedin.com/in/shekhar-meena-a0112690/",
      studentName: "Shekhar Meena",
      role: "Software Development Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2015-6",
      linkedinUrl: "https://www.linkedin.com/in/agarwal-shashank/",
      studentName: "Shashank Agarwal",
      role: "Salesforce Engineer 3",
      companyLogoUrl: "",
      profileImage: "",
    },
  ];
  
// ===============================================================================================
export const Data2016 = [
    {
      id: "2016-1",
      linkedinUrl: "https://www.linkedin.com/in/harshaharyani/",
      studentName: "Harsha Haryani",
      role: "Associate Vice President",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2016-2",
      linkedinUrl: "https://www.linkedin.com/in/techieadarsh/",
      studentName: "Adarsh Singh",
      role: "Software Engineering Manager",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2016-3",
      linkedinUrl: "https://www.linkedin.com/in/yuktijulka/",
      studentName: "Yukti Julka",
      role: "Data Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2016-4",
      linkedinUrl: "https://www.linkedin.com/in/gunjanladdha/",
      studentName: "Gunjan Laddha",
      role: "Senior Talent Acquisition Specialist",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2016-5",
      linkedinUrl: "https://www.linkedin.com/in/alisha-agarwal-bb1901112/",
      studentName: "Alisha Agarwal",
      role: "Consultant",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2016-6",
      linkedinUrl: "https://www.linkedin.com/in/dibakar-prasad-201667113/",
      studentName: "Dibakar Prasad",
      role: "Associate Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
  ];
// ==============================================================================================

export const Data2017 = [
    {
      id: "2017-1",
      linkedinUrl: "https://www.linkedin.com/in/aditya-raman-9a9493129/",
      studentName: "Aditya Raman",
      role: "Software Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-2",
      linkedinUrl: "https://www.linkedin.com/in/raj-aditya/",
      studentName: "Aditya Raj",
      role: "DevOps Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-3",
      linkedinUrl: "https://www.linkedin.com/in/ujjwal-gupta-/",
      studentName: "Ujjwal Gupta",
      role: "Software Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-4",
      linkedinUrl: "https://www.linkedin.com/in/yash-gupta-953bb216a/",
      studentName: "Yash Gupta",
      role: "DevOps Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-5",
      linkedinUrl: "https://www.linkedin.com/in/twinkle-jhamb-a5ba85127/",
      studentName: "Twinkle Jhamb",
      role: "Mainframe Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-6",
      linkedinUrl: "https://www.linkedin.com/in/rahul-mandal-698626144/",
      studentName: "Rahul Mandal",
      role: "Security Analyst",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-7",
      linkedinUrl: "https://www.linkedin.com/in/mahendra-jain/",
      studentName: "Mahendra Lalani",
      role: "Senior Cloud Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-8",
      linkedinUrl: "https://www.linkedin.com/in/mitulsinghal/",
      studentName: "Mitul Singhal",
      role: "Sr. Science Faculty",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-9",
      linkedinUrl: "https://www.linkedin.com/in/sourav-mahesh-64202513b/",
      studentName: "Sourav Mahesh",
      role: "Linux System Admin",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-10",
      linkedinUrl: "https://www.linkedin.com/in/vishantsharma07/",
      studentName: "Vishant Sharma",
      role: "Sr. Lead DevOps Consultant",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-11",
      linkedinUrl: "https://www.linkedin.com/in/bhavishay-sikka/",
      studentName: "Bhavishay Sikka",
      role: "DevOps Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-12",
      linkedinUrl: "https://www.linkedin.com/in/jatin-gupta-181947144/",
      studentName: "Jatin Gupta",
      role: "SDE 3",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-13",
      linkedinUrl: "https://www.linkedin.com/in/tarunjethwani/",
      studentName: "Tarun Jethwani",
      role: "Technical Business Analyst / Platform Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-14",
      linkedinUrl: "https://www.linkedin.com/in/ujjwal-bajaj-68613abb/",
      studentName: "Ujjwal Bajaj",
      role: "Co-Founder",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-15",
      linkedinUrl: "https://www.linkedin.com/in/somya-mudgal-91a82918a/",
      studentName: "Somya Mudgal",
      role: "Cloud Support Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-16",
      linkedinUrl: "https://www.linkedin.com/in/parul-mewara-1605b5125/",
      studentName: "Parul Mewara",
      role: "Senior Test Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-17",
      linkedinUrl: "https://www.linkedin.com/in/darshijain/",
      studentName: "Darshi Jain",
      role: "Account Manager Ad Sales",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-18",
      linkedinUrl: "https://www.linkedin.com/in/vishal-maheshwari-854b41141/",
      studentName: "Vishal Maheshwari",
      role: "Senior Consultant",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-19",
      linkedinUrl: "https://www.linkedin.com/in/dakshita-tiwari-4350a0146/",
      studentName: "Dakshita Tiwari",
      role: "Sourcing Analyst",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-20",
      linkedinUrl: "https://www.linkedin.com/in/sandesh-goyal-07010b146/",
      studentName: "Sandesh Goyal",
      role: "Java Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-21",
      linkedinUrl: "https://www.linkedin.com/in/agarwalankit158/",
      studentName: "Ankit Agarwal",
      role: "Sr. Experience Designer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-22",
      linkedinUrl: "https://www.linkedin.com/in/nitin-jadwal/",
      studentName: "Nitin Jadwal",
      role: "DevOps Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-23",
      linkedinUrl: "https://www.linkedin.com/in/jai3sharma/",
      studentName: "Jatin Sharma",
      role: "Associate Consultant",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-24",
      linkedinUrl: "https://www.linkedin.com/in/aneep-raj-agrawal-961043109/",
      studentName: "Aneep Raj Agrawal",
      role: "Advisor - Data Engineering",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-25",
      linkedinUrl: "https://www.linkedin.com/in/salabh-lahoti-b7a9a0b1/",
      studentName: "Salabh Lahoti",
      role: "Packaged App Development Senior Analyst",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-26",
      linkedinUrl: "https://www.linkedin.com/in/shreya-sharma-8a0ba8100/",
      studentName: "Shreya Sharma",
      role: "MTS at Salesforce",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-27",
      linkedinUrl: "https://www.linkedin.com/in/kumarmayank6746/",
      studentName: "Kumar Mayank",
      role: "GenAI Specialist",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2017-28",
      linkedinUrl: "https://www.linkedin.com/in/riyajain0106/",
      studentName: "Riya Jain",
      role: "Data Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
  ];
  

// ===========================================================================================

export const Data2018 = [
    {
      id: "2018-1",
      linkedinUrl: "https://www.linkedin.com/in/anu7bharil/",
      studentName: "Anubhuti Bharil",
      role: "Senior Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-2",
      linkedinUrl: "https://www.linkedin.com/in/jakshat-desai/",
      studentName: "Jakshat Desai",
      role: "Software Development Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-3",
      linkedinUrl: "https://www.linkedin.com/in/ujjawal-gupta-015ba6168/",
      studentName: "Ujjawal Gupta",
      role: "Member of Technical Staff",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-4",
      linkedinUrl: "https://www.linkedin.com/in/prateekjaindev/",
      studentName: "Prateek Jain",
      role: "DevSecOps Architect",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-5",
      linkedinUrl: "https://www.linkedin.com/in/ashutoshlw/",
      studentName: "Ashutosh Purohit",
      role: "DevOps Engineer 3",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-6",
      linkedinUrl: "https://www.linkedin.com/in/bijendra-sharma-bijen1ghy/",
      studentName: "Bijendra Kumar Sharma",
      role: "Associate Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-7",
      linkedinUrl: "https://www.linkedin.com/in/himanshuyadav96/",
      studentName: "Himanshu Yadav",
      role: "Senior Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-8",
      linkedinUrl: "https://www.linkedin.com/in/kinjal12/",
      studentName: "Kinjal Jain",
      role: "Software Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-9",
      linkedinUrl: "https://www.linkedin.com/in/amrit-raj-623962173/",
      studentName: "Amrit Raj",
      role: "ASIC Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-10",
      linkedinUrl: "https://www.linkedin.com/in/nihal-muktala-382674133/",
      studentName: "Nihal Muktala",
      role: "SDE",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-11",
      linkedinUrl: "https://www.linkedin.com/in/keshav-khatore/",
      studentName: "Keshav Khatore",
      role: "Cloud Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-12",
      linkedinUrl: "https://www.linkedin.com/in/pratibha-jain-78b96712b/",
      studentName: "Pratibha Jain",
      role: "Senior Quality Assurance Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2018-13",
      linkedinUrl: "https://www.linkedin.com/in/pritam-das-4b9197182/",
      studentName: "Pritam Das",
      role: "Senior Analyst",
      companyLogoUrl: "",
      profileImage: "",
    },
  ];
  

// ===============================================================================

export const Data2020 = [
    {
      id: "2020-1",
      linkedinUrl: "https://www.linkedin.com/in/deepak-kumar-971a25106/",
      studentName: "Deepak Kumar",
      role: "Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-2",
      linkedinUrl: "https://www.linkedin.com/in/manish-nehra/",
      studentName: "Manish Nehra",
      role: "DevOps Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-3",
      linkedinUrl: "https://www.linkedin.com/in/aditinirmal/",
      studentName: "Aditi Nirmal",
      role: "Barclays Analyst",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-4",
      linkedinUrl: "https://www.linkedin.com/in/ayushi-sharma-2aa38b169/",
      studentName: "Ayushi Sharma",
      role: "Associate Professional",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-5",
      linkedinUrl: "https://www.linkedin.com/in/aman-miglani-412b6216b/",
      studentName: "Aman Miglani",
      role: "Associate Data Scientist",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-6",
      linkedinUrl: "https://www.linkedin.com/in/vsviveksaini/",
      studentName: "Vivek Saini",
      role: "DevOps Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-7",
      linkedinUrl: "https://www.linkedin.com/in/harshit-jain-hj15/",
      studentName: "Harshit Jain",
      role: "Senior Technical Lead",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-8",
      linkedinUrl: "https://www.linkedin.com/in/rohansinghshekhawat/",
      studentName: "Rohan Singh Shekhawat",
      role: "Founder",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-9",
      linkedinUrl: "https://www.linkedin.com/in/gaurav-b-028209104/",
      studentName: "Gaurav Bhojwani",
      role: "Full Stack Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-10",
      linkedinUrl: "https://www.linkedin.com/in/tushar-goyal-aa8a81192/",
      studentName: "Tushar Goyal",
      role: "AWS Infra Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-11",
      linkedinUrl: "https://www.linkedin.com/in/hema-nakra-1a3683177/",
      studentName: "Hema Nakra",
      role: "Associate Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-12",
      linkedinUrl: "https://www.linkedin.com/in/sandeep-singh-rajawat-615109152/",
      studentName: "Sandeep Singh Rajawat",
      role: "Business Technology Solutions Associate",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-13",
      linkedinUrl: "https://www.linkedin.com/in/sparsh-agrawal-ba7266171/",
      studentName: "Sparsh Agrawal",
      role: "Associate Consultant",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-14",
      linkedinUrl: "https://www.linkedin.com/in/rishabh27sharma/",
      studentName: "Rishabh Sharma",
      role: "Senior Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-15",
      linkedinUrl: "https://www.linkedin.com/in/abhishekchouhanind/",
      studentName: "Abhishek Chouhan",
      role: "DevOps Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-16",
      linkedinUrl: "https://www.linkedin.com/in/abhisheksingh003/",
      studentName: "Abhishek Kumar",
      role: "Not Working",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-17",
      linkedinUrl: "https://www.linkedin.com/in/kunal-jaiswal-1572b6186/",
      studentName: "Kunal Jaiswal",
      role: "SDE",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-18",
      linkedinUrl: "https://www.linkedin.com/in/arpit-sironiya-854455111/",
      studentName: "Arpit Sironiya",
      role: "Not Working",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-19",
      linkedinUrl: "https://www.linkedin.com/in/shailja-tripathi-104168177/",
      studentName: "Shailja Tripathi",
      role: "Azure PaaS Cloud Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-20",
      linkedinUrl: "https://www.linkedin.com/in/nobleblackk/",
      studentName: "Abhishek Sharma",
      role: "Software Development Engineer 2",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-21",
      linkedinUrl: "https://www.linkedin.com/in/shivang121/",
      studentName: "Shivang Agarwal",
      role: "Senior Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-22",
      linkedinUrl: "https://www.linkedin.com/in/rohitbhatia01/",
      studentName: "Rohit Bhatia",
      role: "Software Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-23",
      linkedinUrl: "https://www.linkedin.com/in/hiralrnagda/",
      studentName: "Hiral Rajesh Nagda",
      role: "Graduate Teaching Assistant",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-24",
      linkedinUrl: "https://www.linkedin.com/in/devesh-chitlangia/",
      studentName: "Devesh Chitlangia",
      role: "Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-25",
      linkedinUrl: "https://www.linkedin.com/in/abhishek-kumawat-1899b2181/",
      studentName: "Abhishek Kumawat",
      role: "Information Security (SOX)",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-26",
      linkedinUrl: "https://www.linkedin.com/in/creativesid/",
      studentName: "Siddharth Sharma",
      role: "Senior Creative Director",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-27",
      linkedinUrl: "https://www.linkedin.com/in/pooja-rathore-91990a16a/",
      studentName: "Pooja Rathore",
      role: "Software Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-28",
      linkedinUrl: "https://www.linkedin.com/in/sunil-poricha-70828b155/",
      studentName: "Sunil Poricha",
      role: "Lead DevOps Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-29",
      linkedinUrl: "https://www.linkedin.com/in/mehul20042001/",
      studentName: "Mehul Kulshrestha",
      role: "Senior Software Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-30",
      linkedinUrl: "https://www.linkedin.com/in/rajatrathi90/",
      studentName: "Rajat Rathi",
      role: "Software Development Engineer II",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-31",
      linkedinUrl: "https://www.linkedin.com/in/aayushpawar21/",
      studentName: "Aayush Pawar",
      role: "App/Cloud Specialist",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-32",
      linkedinUrl: "https://www.linkedin.com/in/khushi-gupta-56731217b/",
      studentName: "Khushi Gupta",
      role: "Storage and Operations",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-33",
      linkedinUrl: "https://www.linkedin.com/in/deepti-tiwari-0226/",
      studentName: "Deepti Tiwari",
      role: "Application Developer",
      companyLogoUrl: "",
      profileImage: "",
    },
    {
      id: "2020-34",
      linkedinUrl: "https://www.linkedin.com/in/amrit-raj-623962173/",
      studentName: "Amrit Raj",
      role: "ASIC Engineer",
      companyLogoUrl: "",
      profileImage: "",
    },
  ];
  
// ==================================================================================

export const Data2021 = [
    {
        id: "2021-1",
        linkedinUrl: "https://www.linkedin.com/in/dev-ji-gupta/",
        studentName: "Dev Ji Gupta",
        role: "Java Developer",
        companyLogoUrl: "/assets/company-logos/infosys.png",
        profileImage: "/assets/profiles/dev-ji-gupta.jpg"
    },
    {
        id: "2021-2",
        linkedinUrl: "https://www.linkedin.com/in/shweta-agarwal-200064186/",
        studentName: "Shweta Agarwal",
        role: "Packaged App Development Senior Analyst",
        companyLogoUrl: "/assets/company-logos/accenture.png",
        profileImage: "/assets/profiles/shweta-agarwal.jpg"
    },
    {
        id: "2021-3",
        linkedinUrl: "https://www.linkedin.com/in/mahek-batra/",
        studentName: "Mahek Batra",
        role: "Senior Analyst",
        companyLogoUrl: "/assets/company-logos/ey.png",
        profileImage: "/assets/profiles/mahek-batra.jpg"
    },
    {
        id: "2021-4",
        linkedinUrl: "https://www.linkedin.com/in/vanshita-kashyap-00841a160/",
        studentName: "Vanshita Kashyap",
        role: "Global IT Service Desk Lead",
        companyLogoUrl: "/assets/company-logos/atotech.png",
        profileImage: "/assets/profiles/vanshita-kashyap.jpg"
    },
    {
        id: "2021-5",
        linkedinUrl: "https://www.linkedin.com/in/shailesh-gond-1a8aa320a/",
        studentName: "Shailesh Gond",
        role: "Assistant System Engineer",
        companyLogoUrl: "/assets/company-logos/tcs.png",
        profileImage: "/assets/profiles/shailesh-gond.jpg"
    },
    {
        id: "2021-6",
        linkedinUrl: "https://www.linkedin.com/in/bhupendra-tale95b3b11b4/",
        studentName: "Bhupendra Tale",
        role: "Flutter Developer",
        companyLogoUrl: "/assets/company-logos/syscraft.png",
        profileImage: "/assets/profiles/bhupendra-tale.jpg"
    },
    {
        id: "2021-7",
        linkedinUrl: "https://www.linkedin.com/in/satvik-arya/",
        studentName: "Satvik Arya",
        role: "Course Creator",
        companyLogoUrl: "/assets/company-logos/speak.png",
        profileImage: "/assets/profiles/satvik-arya.jpg"
    },
    {
        id: "2021-8",
        linkedinUrl: "https://www.linkedin.com/in/aadil-khan-03b5301aa/",
        studentName: "Mohd Adil Khan",
        role: "Software Engineer",
        companyLogoUrl: "/assets/company-logos/nagarro.png",
        profileImage: "/assets/profiles/mohd-adil-khan.jpg"
    },
    {
        id: "2021-9",
        linkedinUrl: "https://www.linkedin.com/in/tirupatel/",
        studentName: "Tirth Patel",
        role: "MLOps Engineer",
        companyLogoUrl: "/assets/company-logos/shakudo.png",
        profileImage: "/assets/profiles/tirth-patel.jpg"
    },
    {
        id: "2021-10",
        linkedinUrl: "https://www.linkedin.com/in/amanjhagrolia143/",
        studentName: "Aman Jhagrolia",
        role: "Site Reliability Engineer",
        companyLogoUrl: "/assets/company-logos/zscaler.png",
        profileImage: "/assets/profiles/aman-jhagrolia.jpg"
    },
    {
        id: "2021-11",
        linkedinUrl: "https://www.linkedin.com/in/fareena-shaik/",
        studentName: "Fareena Shaik",
        role: "Data Engineer",
        companyLogoUrl: "/assets/company-logos/danske-bank.png",
        profileImage: "/assets/profiles/fareena-shaik.jpg"
    },
    {
        id: "2021-12",
        linkedinUrl: "https://www.linkedin.com/in/nupur-rathod/",
        studentName: "Nupur Rathod",
        role: "Software Engineer Intern",
        companyLogoUrl: "/assets/company-logos/skippio.png",
        profileImage: "/assets/profiles/nupur-rathod.jpg"
    },
    {
        id: "2021-13",
        linkedinUrl: "https://www.linkedin.com/in/avijitd22/",
        studentName: "Avijit Das",
        role: "Full Stack Developer",
        companyLogoUrl: "/assets/company-logos/adengage.png",
        profileImage: "/assets/profiles/avijit-das.jpg"
    },
    {
        id: "2021-14",
        linkedinUrl: "https://www.linkedin.com/in/ankit-pramanik-devops/",
        studentName: "Ankit Pramanik",
        role: "DevOps Engineer",
        companyLogoUrl: "/assets/company-logos/persistent-systems.png",
        profileImage: "/assets/profiles/ankit-pramanik.jpg"
    },
    {
        id: "2021-15",
        linkedinUrl: "https://www.linkedin.com/in/pramod-kumar-gupta/",
        studentName: "Pramod Kumar Gupta",
        role: "DevOps Intern",
        companyLogoUrl: "/assets/company-logos/signzy.png",
        profileImage: "/assets/profiles/pramod-kumar-gupta.jpg"
    },
    {
        id: "2021-16",
        linkedinUrl: "https://www.linkedin.com/in/bankamanibhargava/",
        studentName: "Mani Bhargava Banka",
        role: "Associate",
        companyLogoUrl: "/assets/company-logos/cognizant.png",
        profileImage: "/assets/profiles/mani-bhargava-banka.jpg"
    },
    {
        id: "2021-17",
        linkedinUrl: "https://www.linkedin.com/in/maanassingal/",
        studentName: "Maanas Singal",
        role: "AI/ML | Cloud",
        companyLogoUrl: "/assets/company-logos/dit-university.png",
        profileImage: "/assets/profiles/maanas-singal.jpg"
    },
    {
        id: "2021-18",
        linkedinUrl: "https://www.linkedin.com/in/jayvardhanprajapat/",
        studentName: "Jayvardhan Prajapat",
        role: "Cloud Engineer - II",
        companyLogoUrl: "/assets/company-logos/virtuecloud.png",
        profileImage: "/assets/profiles/jayvardhan-prajapat.jpg"
    },
    {
        id: "2021-19",
        linkedinUrl: "https://www.linkedin.com/in/rahul-kumar87/",
        studentName: "Rahul Kumar",
        role: "DevOps Engineer",
        companyLogoUrl: "/assets/company-logos/squareops.png",
        profileImage: "/assets/profiles/rahul-kumar.jpg"
    }
];

// =================================================================================

export const Data2022 = [
    {
        id: "2022-1",
        linkedinUrl: "https://www.linkedin.com/in/gaurav-kumar-shukla/",
        studentName: "Gaurav Kumar",
        role: "Software Engineer",
        companyLogoUrl: "/assets/company-logos/finvisage.png",
        profileImage: "/assets/profiles/gaurav-kumar.jpg"
    },
    {
        id: "2022-2",
        linkedinUrl: "https://www.linkedin.com/in/ashwingunadeep/",
        studentName: "Ashwin Gunadeep",
        role: "Product Manager",
        companyLogoUrl: "/assets/company-logos/carestack.png",
        profileImage: "/assets/profiles/ashwin-gunadeep.jpg"
    },
    {
        id: "2022-3",
        linkedinUrl: "https://www.linkedin.com/in/himanshu-ganglani-112b6b11b/",
        studentName: "Himanshu Ganglani",
        role: "Software Engineer",
        companyLogoUrl: "/assets/company-logos/simpplr.png",
        profileImage: "/assets/profiles/himanshu-ganglani.jpg"
    },
    {
        id: "2022-4",
        linkedinUrl: "https://www.linkedin.com/in/alokikkanchan/",
        studentName: "Alokik Kanchan",
        role: "Software Engineer",
        companyLogoUrl: "/assets/company-logos/hashedin.png",
        profileImage: "/assets/profiles/alokik-kanchan.jpg"
    },
    {
        id: "2022-5",
        linkedinUrl: "https://www.linkedin.com/in/ashu-mish/",
        studentName: "Ashutosh Mishra",
        role: "Senior Product Engineer",
        companyLogoUrl: "/assets/company-logos/temenos.png",
        profileImage: "/assets/profiles/ashutosh-mishra.jpg"
    },
    {
        id: "2022-6",
        linkedinUrl: "https://www.linkedin.com/in/avaneesh-shukla-34977615b/",
        studentName: "Avaneesh Shukla",
        role: "Specialist Programmer",
        companyLogoUrl: "/assets/company-logos/infosys.png",
        profileImage: "/assets/profiles/avaneesh-shukla.jpg"
    },
    {
        id: "2022-7",
        linkedinUrl: "https://www.linkedin.com/in/kishan-kumar-3896a013a/",
        studentName: "Kishan Kumar",
        role: "Penetration Tester",
        companyLogoUrl: "/assets/company-logos/admiral-group.png",
        profileImage: "/assets/profiles/kishan-kumar.jpg"
    },
    {
        id: "2022-8",
        linkedinUrl: "https://www.linkedin.com/in/upasana-tailor-b24539152/",
        studentName: "Upasana Tailor",
        role: "Web Dev Lecturer",
        companyLogoUrl: "/assets/company-logos/dci.png",
        profileImage: "/assets/profiles/upasana-tailor.jpg"
    },
    {
        id: "2022-9",
        linkedinUrl: "https://www.linkedin.com/in/gaurav-khandelwal-49970715b/",
        studentName: "Gaurav Khandelwal",
        role: "Teaching Assistant",
        companyLogoUrl: "/assets/company-logos/iiita.png",
        profileImage: "/assets/profiles/gaurav-khandelwal.jpg"
    },
    {
        id: "2022-10",
        linkedinUrl: "https://www.linkedin.com/in/srinjoy-sur/",
        studentName: "Srinjoy Sur",
        role: "Junior Software Engineer Intern",
        companyLogoUrl: "/assets/company-logos/epam.png",
        profileImage: "/assets/profiles/srinjoy-sur.jpg"
    },
    {
        id: "2022-11",
        linkedinUrl: "https://www.linkedin.com/in/7srambo/",
        studentName: "S Rahul",
        role: "Information Security Analyst",
        companyLogoUrl: "/assets/company-logos/nuk9.png",
        profileImage: "/assets/profiles/s-rahul.jpg"
    },
    {
        id: "2022-12",
        linkedinUrl: "https://www.linkedin.com/in/mohit-singh-tomar/",
        studentName: "Mohit Singh Tomar",
        role: "DevOps Engineer",
        companyLogoUrl: "/assets/company-logos/nerdapp.png",
        profileImage: "/assets/profiles/mohit-singh-tomar.jpg"
    },
    {
        id: "2022-13",
        linkedinUrl: "https://www.linkedin.com/in/mona-chawla/",
        studentName: "Mona Chawla",
        role: "Associate DevOps Engineer",
        companyLogoUrl: "/assets/company-logos/squareops.png",
        profileImage: "/assets/profiles/mona-chawla.jpg"
    },
    {
        id: "2022-14",
        linkedinUrl: "https://www.linkedin.com/in/tanayofficial/",
        studentName: "Tanay Srivastava",
        role: "Not Working",
        companyLogoUrl: "/assets/company-logos/not-working.png",
        profileImage: "/assets/profiles/tanay-srivastava.jpg"
    },
    {
        id: "2022-15",
        linkedinUrl: "https://www.linkedin.com/in/paridhi-dahake-237bb8200/",
        studentName: "Paridhi Dahake",
        role: "Not Working",
        companyLogoUrl: "/assets/company-logos/not-working.png",
        profileImage: "/assets/profiles/paridhi-dahake.jpg"
    },
    {
        id: "2022-16",
        linkedinUrl: "https://www.linkedin.com/in/sakshi-ghogre-68b075170/",
        studentName: "Sakshi Ghogre",
        role: "Software Analyst",
        companyLogoUrl: "/assets/company-logos/capgemini.png",
        profileImage: "/assets/profiles/sakshi-ghogre.jpg"
    },
    {
        id: "2022-17",
        linkedinUrl: "https://www.linkedin.com/in/darshan-paliwal-a1b246201/",
        studentName: "Darshan Paliwal",
        role: "Assistant Team Lead",
        companyLogoUrl: "/assets/company-logos/vidhyashala.png",
        profileImage: "/assets/profiles/darshan-paliwal.jpg"
    },
    {
        id: "2022-18",
        linkedinUrl: "https://www.linkedin.com/in/akshitaparakh/",
        studentName: "Akshita Parakh",
        role: "Systems Engineer",
        companyLogoUrl: "/assets/company-logos/tcs.png",
        profileImage: "/assets/profiles/akshita-parakh.jpg"
    }
];